prod:
  vars:
    ansible_user: "ubuntu"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  hosts:
    AnsibleProd:
      ansible_host: "172.31.91.203"
staging:
  vars:
    ansible_user: "ubuntu"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  hosts:
    AnsibleStaging:
      ansible_host: "172.31.88.182"
master:
   vars:
     ansible_connection: local
     ansible_user: "ubuntu"
   hosts:
     AnsibleMaster:
       ansible_host: "localhost"
